2020-01-31 21:30:03,533 DEBUG my_server.py main При запуске переданы аргументы: Namespace(ip_addr='127.0.0.1', port=7777)
2020-01-31 21:30:03,538 INFO my_server.py main Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: 127.0.0.1. Если адрес не указан, принимаются соединения с любых адресов.
2020-01-31 21:30:09,950 INFO my_server.py main Установлено соедение с Клиентом ('127.0.0.1', 54392)
2020-01-31 21:30:09,954 ERROR my_server.py main Не удалось декодировать Json строку, полученную от клиента ('127.0.0.1', 54392). Соединение закрывается.
2020-01-31 21:31:03,649 INFO my_server.py main Установлено соедение с Клиентом ('127.0.0.1', 54398)
2020-01-31 21:31:03,653 ERROR my_server.py main Не удалось декодировать Json строку, полученную от клиента ('127.0.0.1', 54398). Соединение закрывается.
2020-01-31 21:32:30,581 INFO my_server.py main Установлено соедение с Клиентом ('127.0.0.1', 54401)
2020-01-31 21:32:30,585 ERROR my_server.py main Не удалось декодировать Json строку, полученную от клиента ('127.0.0.1', 54401). Соединение закрывается.
2020-01-31 21:33:14,088 INFO my_server.py main Установлено соедение с Клиентом ('127.0.0.1', 54402)
2020-01-31 21:33:14,093 ERROR my_server.py main Не удалось декодировать Json строку, полученную от клиента ('127.0.0.1', 54402). Соединение закрывается.
2020-01-31 21:33:16,585 INFO my_server.py main Установлено соедение с Клиентом ('127.0.0.1', 54403)
2020-01-31 21:33:16,588 ERROR my_server.py main Не удалось декодировать Json строку, полученную от клиента ('127.0.0.1', 54403). Соединение закрывается.
2020-01-31 21:33:36,312 INFO my_server.py main Установлено соедение с Клиентом ('127.0.0.1', 54404)
2020-01-31 21:33:36,313 DEBUG decorators.py log_writter вызывается функция generate_presence_msg из модуля __main__функции переданы параметры (),{}функция вернула {'action': 'presence', 'time': 'Fri Jan 31 21:33:36 2020', 'user': {'account_name': 'Guest'}}.была вызвана из [<FrameSummary file C:/Users/Сергей/PycharmProjects/client-server_apps/lesson_2/my_version/my_client.py, line 96 in <module>>, <FrameSummary file C:/Users/Сергей/PycharmProjects/client-server_apps/lesson_2/my_version/my_client.py, line 80 in main>, <FrameSummary file C:\Users\Сергей\PycharmProjects\client-server_apps\lesson_2\my_version\decorators.py, line 25 in log_writter>]
2020-01-31 21:33:36,313 DEBUG my_server.py main От клиента ('127.0.0.1', 54404) получено сообщение: {'action': 'presence', 'time': 'Fri Jan 31 21:33:36 2020', 'user': {'account_name': 'Guest'}}
2020-01-31 21:35:17,513 DEBUG my_server.py main При запуске переданы аргументы: Namespace(ip_addr='127.0.0.1', port=7777)
2020-01-31 21:35:17,514 INFO my_server.py main Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: 127.0.0.1. Если адрес не указан, принимаются соединения с любых адресов.
2020-01-31 21:35:22,504 INFO my_server.py main Установлено соедение с Клиентом ('127.0.0.1', 54406)
2020-01-31 21:35:22,508 ERROR my_server.py main Не удалось декодировать Json строку, полученную от клиента ('127.0.0.1', 54406). Соединение закрывается.
2020-01-31 21:36:44,832 INFO my_server.py main Установлено соедение с Клиентом ('127.0.0.1', 54409)
2020-01-31 21:36:44,832 DEBUG decorators.py log_writter вызывается функция generate_presence_msg из модуля __main__функции переданы параметры (),{}функция вернула {'action': 'presence', 'time': 'Fri Jan 31 21:36:44 2020', 'user': {'account_name': 'Guest'}}.была вызвана из main()
2020-01-31 21:36:44,833 DEBUG my_server.py main От клиента ('127.0.0.1', 54409) получено сообщение: {'action': 'presence', 'time': 'Fri Jan 31 21:36:44 2020', 'user': {'account_name': 'Guest'}}
2020-01-31 21:37:17,893 DEBUG my_server.py main При запуске переданы аргументы: Namespace(ip_addr='127.0.0.1', port=7777)
2020-01-31 21:37:17,894 INFO my_server.py main Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: 127.0.0.1. Если адрес не указан, принимаются соединения с любых адресов.
2020-01-31 21:37:23,793 INFO my_server.py main Установлено соедение с Клиентом ('127.0.0.1', 54412)
2020-01-31 21:37:23,793 DEBUG decorators.py log_writter вызывается функция generate_presence_msg из модуля __main__функции переданы параметры (),{}функция вернула {'action': 'presence', 'time': 'Fri Jan 31 21:37:23 2020', 'user': {'account_name': 'Guest'}}.была вызвана из ['File', '"C:/Users/Сергей/PycharmProjects/client-server_apps/lesson_2/my_version/my_client.py",', 'line', '96,', 'in', '<module>', 'main()']
2020-01-31 21:37:23,794 DEBUG my_server.py main От клиента ('127.0.0.1', 54412) получено сообщение: {'action': 'presence', 'time': 'Fri Jan 31 21:37:23 2020', 'user': {'account_name': 'Guest'}}
2020-01-31 21:37:23,795 DEBUG decorators.py log_writter вызывается функция process_client_message из модуля __main__функции переданы параметры ({'action': 'presence', 'time': 'Fri Jan 31 21:37:23 2020', 'user': {'account_name': 'Guest'}},),{}функция вернула {'response': 200}.была вызвана из ['File', '"C:/Users/Сергей/PycharmProjects/client-server_apps/lesson_2/my_version/my_server.py",', 'line', '98,', 'in', '<module>', 'main()']
2020-01-31 21:37:23,795 INFO my_server.py main Cформирован ответ клиенту "{'response': 200}"
2020-01-31 21:37:23,795 INFO my_server.py main Клиенту ('127.0.0.1', 54412) отправлено сообщение "{'response': 200}"
2020-01-31 21:37:23,795 INFO my_server.py main Соединение c клиентом ('127.0.0.1', 54412) закрывается
2020-01-31 21:37:23,795 DEBUG decorators.py log_writter вызывается функция process_server_ans из модуля __main__функции переданы параметры ({'response': 200},),{}функция вернула 200 : OK.была вызвана из ['File', '"C:/Users/Сергей/PycharmProjects/client-server_apps/lesson_2/my_version/my_client.py",', 'line', '96,', 'in', '<module>', 'main()']
2020-01-31 21:38:03,522 INFO my_server.py main Установлено соедение с Клиентом ('127.0.0.1', 54413)
2020-01-31 21:38:03,523 DEBUG decorators.py log_writter вызывается функция generate_presence_msg из модуля __main__функции переданы параметры (),{}функция вернула {'action': 'presence', 'time': 'Fri Jan 31 21:38:03 2020', 'user': {'account_name': 'Guest'}}.была вызвана из main()
2020-01-31 21:38:03,523 DEBUG my_server.py main От клиента ('127.0.0.1', 54413) получено сообщение: {'action': 'presence', 'time': 'Fri Jan 31 21:38:03 2020', 'user': {'account_name': 'Guest'}}
2020-01-31 21:38:03,524 DEBUG decorators.py log_writter вызывается функция process_client_message из модуля __main__функции переданы параметры ({'action': 'presence', 'time': 'Fri Jan 31 21:38:03 2020', 'user': {'account_name': 'Guest'}},),{}функция вернула {'response': 200}.была вызвана из ['File', '"C:/Users/Сергей/PycharmProjects/client-server_apps/lesson_2/my_version/my_server.py",', 'line', '98,', 'in', '<module>', 'main()']
2020-01-31 21:38:03,524 INFO my_server.py main Cформирован ответ клиенту "{'response': 200}"
2020-01-31 21:38:03,525 INFO my_server.py main Клиенту ('127.0.0.1', 54413) отправлено сообщение "{'response': 200}"
2020-01-31 21:38:03,525 INFO my_server.py main Соединение c клиентом ('127.0.0.1', 54413) закрывается
2020-01-31 21:38:03,525 DEBUG decorators.py log_writter вызывается функция process_server_ans из модуля __main__функции переданы параметры ({'response': 200},),{}функция вернула 200 : OK.была вызвана из main()
2020-01-31 21:39:07,077 INFO my_server.py main Установлено соедение с Клиентом ('127.0.0.1', 54414)
2020-01-31 21:39:07,086 DEBUG decorators.py log_writter вызывается функция generate_presence_msg из модуля __main__функции переданы параметры (),{}функция вернула {'action': 'presence', 'time': 'Fri Jan 31 21:39:07 2020', 'user': {'account_name': 'Guest'}}.была вызвана из main()Вызов из функции main
2020-01-31 21:39:07,087 DEBUG my_server.py main От клиента ('127.0.0.1', 54414) получено сообщение: {'action': 'presence', 'time': 'Fri Jan 31 21:39:07 2020', 'user': {'account_name': 'Guest'}}
2020-01-31 21:39:07,087 DEBUG decorators.py log_writter вызывается функция process_client_message из модуля __main__функции переданы параметры ({'action': 'presence', 'time': 'Fri Jan 31 21:39:07 2020', 'user': {'account_name': 'Guest'}},),{}функция вернула {'response': 200}.была вызвана из ['File', '"C:/Users/Сергей/PycharmProjects/client-server_apps/lesson_2/my_version/my_server.py",', 'line', '98,', 'in', '<module>', 'main()']
2020-01-31 21:39:07,087 INFO my_server.py main Cформирован ответ клиенту "{'response': 200}"
2020-01-31 21:39:07,088 INFO my_server.py main Клиенту ('127.0.0.1', 54414) отправлено сообщение "{'response': 200}"
2020-01-31 21:39:07,088 INFO my_server.py main Соединение c клиентом ('127.0.0.1', 54414) закрывается
2020-01-31 21:39:07,089 DEBUG decorators.py log_writter вызывается функция process_server_ans из модуля __main__функции переданы параметры ({'response': 200},),{}функция вернула 200 : OK.была вызвана из main()Вызов из функции main
2020-01-31 21:39:58,969 INFO my_server.py main Установлено соедение с Клиентом ('127.0.0.1', 54420)
2020-01-31 21:39:58,987 DEBUG decorators.py log_writter вызывается функция generate_presence_msg из модуля __main__функции переданы параметры (),{}функция вернула {'action': 'presence', 'time': 'Fri Jan 31 21:39:58 2020', 'user': {'account_name': 'Guest'}}.была вызвана из main()Вызов из функции FrameInfo(frame=<frame at 0x000002293C1C24B8, file 'C:/Users/Сергей/PycharmProjects/client-server_apps/lesson_2/my_version/my_client.py', line 80, code main>, filename='C:/Users/Сергей/PycharmProjects/client-server_apps/lesson_2/my_version/my_client.py', lineno=80, function='main', code_context=['    message = generate_presence_msg()\n'], index=0)
2020-01-31 21:39:58,987 DEBUG my_server.py main От клиента ('127.0.0.1', 54420) получено сообщение: {'action': 'presence', 'time': 'Fri Jan 31 21:39:58 2020', 'user': {'account_name': 'Guest'}}
2020-01-31 21:39:58,988 DEBUG decorators.py log_writter вызывается функция process_client_message из модуля __main__функции переданы параметры ({'action': 'presence', 'time': 'Fri Jan 31 21:39:58 2020', 'user': {'account_name': 'Guest'}},),{}функция вернула {'response': 200}.была вызвана из ['File', '"C:/Users/Сергей/PycharmProjects/client-server_apps/lesson_2/my_version/my_server.py",', 'line', '98,', 'in', '<module>', 'main()']
2020-01-31 21:39:58,988 INFO my_server.py main Cформирован ответ клиенту "{'response': 200}"
2020-01-31 21:39:58,989 INFO my_server.py main Клиенту ('127.0.0.1', 54420) отправлено сообщение "{'response': 200}"
2020-01-31 21:39:58,989 INFO my_server.py main Соединение c клиентом ('127.0.0.1', 54420) закрывается
2020-01-31 21:39:58,990 DEBUG decorators.py log_writter вызывается функция process_server_ans из модуля __main__функции переданы параметры ({'response': 200},),{}функция вернула 200 : OK.была вызвана из main()Вызов из функции FrameInfo(frame=<frame at 0x000002293C1C24B8, file 'C:/Users/Сергей/PycharmProjects/client-server_apps/lesson_2/my_version/my_client.py', line 83, code main>, filename='C:/Users/Сергей/PycharmProjects/client-server_apps/lesson_2/my_version/my_client.py', lineno=83, function='main', code_context=['        answer = process_server_ans(get_message(client_sock))\n'], index=0)
2020-01-31 21:40:37,277 INFO my_server.py main Установлено соедение с Клиентом ('127.0.0.1', 54421)
2020-01-31 21:40:37,277 DEBUG decorators.py log_writter вызывается функция generate_presence_msg из модуля __main__функции переданы параметры (),{}функция вернула {'action': 'presence', 'time': 'Fri Jan 31 21:40:37 2020', 'user': {'account_name': 'Guest'}}.была вызвана из main()
2020-01-31 21:40:37,278 DEBUG my_server.py main От клиента ('127.0.0.1', 54421) получено сообщение: {'action': 'presence', 'time': 'Fri Jan 31 21:40:37 2020', 'user': {'account_name': 'Guest'}}
2020-01-31 21:40:37,279 DEBUG decorators.py log_writter вызывается функция process_client_message из модуля __main__функции переданы параметры ({'action': 'presence', 'time': 'Fri Jan 31 21:40:37 2020', 'user': {'account_name': 'Guest'}},),{}функция вернула {'response': 200}.была вызвана из ['File', '"C:/Users/Сергей/PycharmProjects/client-server_apps/lesson_2/my_version/my_server.py",', 'line', '98,', 'in', '<module>', 'main()']
2020-01-31 21:40:37,279 INFO my_server.py main Cформирован ответ клиенту "{'response': 200}"
2020-01-31 21:40:37,279 INFO my_server.py main Клиенту ('127.0.0.1', 54421) отправлено сообщение "{'response': 200}"
2020-01-31 21:40:37,279 INFO my_server.py main Соединение c клиентом ('127.0.0.1', 54421) закрывается
2020-01-31 21:40:37,280 DEBUG decorators.py log_writter вызывается функция process_server_ans из модуля __main__функции переданы параметры ({'response': 200},),{}функция вернула 200 : OK.была вызвана из main()
2020-01-31 21:44:02,370 INFO my_server.py main Установлено соедение с Клиентом ('127.0.0.1', 54426)
2020-01-31 21:44:02,371 DEBUG decorators.py log_writter вызывается функция generate_presence_msg из модуля __main__функции переданы параметры (),{}функция вернула {'action': 'presence', 'time': 'Fri Jan 31 21:44:02 2020', 'user': {'account_name': 'Guest'}}.была вызвана из main()
2020-01-31 21:44:02,371 DEBUG my_server.py main От клиента ('127.0.0.1', 54426) получено сообщение: {'action': 'presence', 'time': 'Fri Jan 31 21:44:02 2020', 'user': {'account_name': 'Guest'}}
2020-01-31 21:44:02,372 DEBUG decorators.py log_writter вызывается функция process_client_message из модуля __main__функции переданы параметры ({'action': 'presence', 'time': 'Fri Jan 31 21:44:02 2020', 'user': {'account_name': 'Guest'}},),{}функция вернула {'response': 200}.была вызвана из ['File', '"C:/Users/Сергей/PycharmProjects/client-server_apps/lesson_2/my_version/my_server.py",', 'line', '98,', 'in', '<module>', 'main()']
2020-01-31 21:44:02,372 INFO my_server.py main Cформирован ответ клиенту "{'response': 200}"
2020-01-31 21:44:02,372 INFO my_server.py main Клиенту ('127.0.0.1', 54426) отправлено сообщение "{'response': 200}"
2020-01-31 21:44:02,372 INFO my_server.py main Соединение c клиентом ('127.0.0.1', 54426) закрывается
2020-01-31 21:44:02,373 DEBUG decorators.py log_writter вызывается функция process_server_ans из модуля __main__функции переданы параметры ({'response': 200},),{}функция вернула 200 : OK.была вызвана из main()
2020-01-31 21:47:08,703 DEBUG my_server.py main При запуске переданы аргументы: Namespace(ip_addr='127.0.0.1', port=7777)
2020-01-31 21:47:08,705 INFO my_server.py main Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: 127.0.0.1. Если адрес не указан, принимаются соединения с любых адресов.
2020-01-31 21:47:14,009 INFO my_server.py main Установлено соедение с Клиентом ('127.0.0.1', 54430)
2020-01-31 21:47:14,010 DEBUG decorators.py log_writter вызывается функция generate_presence_msg из модуля __main__функции переданы параметры (),{}функция вернула {'action': 'presence', 'time': 'Fri Jan 31 21:47:14 2020', 'user': {'account_name': 'Guest'}}.была вызвана из main()
2020-01-31 21:47:14,010 DEBUG my_server.py main От клиента ('127.0.0.1', 54430) получено сообщение: {'action': 'presence', 'time': 'Fri Jan 31 21:47:14 2020', 'user': {'account_name': 'Guest'}}
2020-01-31 21:47:14,011 DEBUG decorators.py log_writter вызывается функция process_client_message из модуля __main__функции переданы параметры ({'action': 'presence', 'time': 'Fri Jan 31 21:47:14 2020', 'user': {'account_name': 'Guest'}},),{}функция вернула {'response': 200}.была вызвана из main()
2020-01-31 21:47:14,011 INFO my_server.py main Cформирован ответ клиенту "{'response': 200}"
2020-01-31 21:47:14,011 INFO my_server.py main Клиенту ('127.0.0.1', 54430) отправлено сообщение "{'response': 200}"
2020-01-31 21:47:14,011 INFO my_server.py main Соединение c клиентом ('127.0.0.1', 54430) закрывается
2020-01-31 21:47:14,012 DEBUG decorators.py log_writter вызывается функция process_server_ans из модуля __main__функции переданы параметры ({'response': 200},),{}функция вернула 200 : OK.была вызвана из main()
2020-01-31 21:50:44,798 INFO my_server.py main Установлено соедение с Клиентом ('127.0.0.1', 54436)
2020-01-31 21:50:44,798 DEBUG decorators.py log_writter вызывается функция generate_presence_msg из модуля __main__функции переданы параметры (),{}функция вернула {'action': 'presence', 'time': 'Fri Jan 31 21:50:44 2020', 'user': {'account_name': 'Guest'}}.была вызвана из main()
2020-01-31 21:50:44,799 DEBUG my_server.py main От клиента ('127.0.0.1', 54436) получено сообщение: {'action': 'presence', 'time': 'Fri Jan 31 21:50:44 2020', 'user': {'account_name': 'Guest'}}
2020-01-31 21:50:44,799 DEBUG decorators.py log_writter вызывается функция process_client_message из модуля __main__функции переданы параметры ({'action': 'presence', 'time': 'Fri Jan 31 21:50:44 2020', 'user': {'account_name': 'Guest'}},),{}функция вернула {'response': 200}.была вызвана из main()
2020-01-31 21:50:44,800 INFO my_server.py main Cформирован ответ клиенту "{'response': 200}"
2020-01-31 21:50:44,800 INFO my_server.py main Клиенту ('127.0.0.1', 54436) отправлено сообщение "{'response': 200}"
2020-01-31 21:50:44,800 INFO my_server.py main Соединение c клиентом ('127.0.0.1', 54436) закрывается
2020-01-31 21:50:44,800 DEBUG decorators.py log_writter вызывается функция process_server_ans из модуля __main__функции переданы параметры ({'response': 200},),{}функция вернула 200 : OK.была вызвана из main()
2020-01-31 21:58:38,501 DEBUG my_server.py main При запуске переданы аргументы: Namespace(ip_addr='127.0.0.1', port=7777)
2020-01-31 21:58:38,503 INFO my_server.py main Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: 127.0.0.1. Если адрес не указан, принимаются соединения с любых адресов.
2020-01-31 23:20:42,783 DEBUG my_server.py main При запуске переданы аргументы: Namespace(ip_addr='127.0.0.1', port=7777)
2020-01-31 23:20:42,785 INFO my_server.py main Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: 127.0.0.1. Если адрес не указан, принимаются соединения с любых адресов.
2020-01-31 23:20:46,657 INFO my_server.py main Установлено соедение с Клиентом ('127.0.0.1', 55036)
2020-01-31 23:20:46,658 DEBUG decorators.py log_writter вызывается функция generate_presence_msg из модуля __main__функции переданы параметры (),{}функция вернула {'action': 'presence', 'time': 'Fri Jan 31 23:20:46 2020', 'user': {'account_name': 'Guest'}}.была вызвана из main()
2020-01-31 23:20:46,659 DEBUG my_server.py main От клиента ('127.0.0.1', 55036) получено сообщение: {'action': 'presence', 'time': 'Fri Jan 31 23:20:46 2020', 'user': {'account_name': 'Guest'}}
2020-01-31 23:20:46,660 DEBUG decorators.py log_writter вызывается функция process_client_message из модуля __main__функции переданы параметры ({'action': 'presence', 'time': 'Fri Jan 31 23:20:46 2020', 'user': {'account_name': 'Guest'}},),{}функция вернула {'response': 200}.была вызвана из main()
2020-01-31 23:20:46,660 INFO my_server.py main Cформирован ответ клиенту "{'response': 200}"
2020-01-31 23:20:46,660 INFO my_server.py main Клиенту ('127.0.0.1', 55036) отправлено сообщение "{'response': 200}"
2020-01-31 23:20:46,660 INFO my_server.py main Соединение c клиентом ('127.0.0.1', 55036) закрывается
2020-01-31 23:20:46,660 DEBUG decorators.py log_writter вызывается функция process_server_ans из модуля __main__функции переданы параметры ({'response': 200},),{}функция вернула 200 : OK.была вызвана из main()
2020-01-31 23:21:11,585 INFO my_server.py main Установлено соедение с Клиентом ('127.0.0.1', 55037)
2020-01-31 23:21:11,585 DEBUG decorators.py log_writter вызывается функция generate_presence_msg из модуля __main__функции переданы параметры (),{}функция вернула {'action': 'presence', 'time': 'Fri Jan 31 23:21:11 2020', 'user': {'account_name': 'Guest'}}.была вызвана из main()
2020-01-31 23:21:11,586 DEBUG my_server.py main От клиента ('127.0.0.1', 55037) получено сообщение: {'action': 'presence', 'time': 'Fri Jan 31 23:21:11 2020', 'user': {'account_name': 'Guest'}}
2020-01-31 23:21:11,586 DEBUG decorators.py log_writter вызывается функция process_client_message из модуля __main__функции переданы параметры ({'action': 'presence', 'time': 'Fri Jan 31 23:21:11 2020', 'user': {'account_name': 'Guest'}},),{}функция вернула {'response': 200}.была вызвана из main()
2020-01-31 23:21:11,586 INFO my_server.py main Cформирован ответ клиенту "{'response': 200}"
2020-01-31 23:21:11,586 INFO my_server.py main Клиенту ('127.0.0.1', 55037) отправлено сообщение "{'response': 200}"
2020-01-31 23:21:11,587 INFO my_server.py main Соединение c клиентом ('127.0.0.1', 55037) закрывается
2020-01-31 23:21:11,587 DEBUG decorators.py log_writter вызывается функция process_server_ans из модуля __main__функции переданы параметры ({'response': 200},),{}функция вернула 200 : OK.была вызвана из main()
2020-01-31 23:25:18,759 INFO my_server.py main Установлено соедение с Клиентом ('127.0.0.1', 55043)
2020-01-31 23:25:18,760 DEBUG decorators.py log_writter вызывается функция generate_presence_msg из модуля __main__функции переданы параметры (),{}функция вернула {'action': 'presence', 'time': 'Fri Jan 31 23:25:18 2020', 'user': {'account_name': 'Guest'}}.была вызвана из main()
2020-01-31 23:25:18,760 DEBUG my_server.py main От клиента ('127.0.0.1', 55043) получено сообщение: {'action': 'presence', 'time': 'Fri Jan 31 23:25:18 2020', 'user': {'account_name': 'Guest'}}
2020-01-31 23:25:18,761 DEBUG decorators.py log_writter вызывается функция process_client_message из модуля __main__функции переданы параметры ({'action': 'presence', 'time': 'Fri Jan 31 23:25:18 2020', 'user': {'account_name': 'Guest'}},),{}функция вернула {'response': 200}.была вызвана из main()
2020-01-31 23:25:18,761 INFO my_server.py main Cформирован ответ клиенту "{'response': 200}"
2020-01-31 23:25:18,761 INFO my_server.py main Клиенту ('127.0.0.1', 55043) отправлено сообщение "{'response': 200}"
2020-01-31 23:25:18,761 INFO my_server.py main Соединение c клиентом ('127.0.0.1', 55043) закрывается
2020-01-31 23:25:18,761 DEBUG decorators.py log_writter вызывается функция process_server_ans из модуля __main__функции переданы параметры ({'response': 200},),{}функция вернула 200 : OK.была вызвана из main()
2020-01-31 23:29:24,386 DEBUG my_server.py main При запуске переданы аргументы: Namespace(ip_addr='127.0.0.1', port=7777)
2020-01-31 23:29:24,388 INFO my_server.py main Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: 127.0.0.1. Если адрес не указан, принимаются соединения с любых адресов.
2020-01-31 23:29:26,547 INFO my_server.py main Установлено соедение с Клиентом ('127.0.0.1', 55055)
2020-01-31 23:29:26,547 DEBUG decorators.py log_writter вызывается функция generate_presence_msg из модуля __main__функции переданы параметры (),{}функция вернула {'action': 'presence', 'time': 'Fri Jan 31 23:29:26 2020', 'user': {'account_name': 'Guest'}}.была вызвана из main()
2020-01-31 23:29:26,548 DEBUG my_server.py main От клиента ('127.0.0.1', 55055) получено сообщение: {'action': 'presence', 'time': 'Fri Jan 31 23:29:26 2020', 'user': {'account_name': 'Guest'}}
2020-01-31 23:29:26,549 DEBUG decorators.py log_writter вызывается функция process_client_message из модуля __main__функции переданы параметры ({'action': 'presence', 'time': 'Fri Jan 31 23:29:26 2020', 'user': {'account_name': 'Guest'}},),{}функция вернула {'response': 200}.была вызвана из main()
2020-01-31 23:29:26,549 INFO my_server.py main Cформирован ответ клиенту "{'response': 200}"
2020-01-31 23:29:26,549 INFO my_server.py main Клиенту ('127.0.0.1', 55055) отправлено сообщение "{'response': 200}"
2020-01-31 23:29:26,549 INFO my_server.py main Соединение c клиентом ('127.0.0.1', 55055) закрывается
2020-01-31 23:29:26,561 DEBUG decorators.py log_writter вызывается функция process_server_ans из модуля __main__функции переданы параметры ({'response': 200},),{}функция вернула 200 : OK.была вызвана из main()
2020-02-01 10:28:01,483 INFO my_server.py main Установлено соедение с Клиентом ('127.0.0.1', 55997)
2020-02-01 10:28:05,129 DEBUG decorators.py log_writter вызывается функция generate_presence_msg из модуля __main__функции переданы параметры (),{}функция вернула {'action': 'presence', 'time': 'Sat Feb  1 10:28:05 2020', 'user': {'account_name': 'Guest'}}.была вызвана из main()
2020-02-01 10:28:07,589 DEBUG my_server.py main От клиента ('127.0.0.1', 55997) получено сообщение: {'action': 'presence', 'time': 'Sat Feb  1 10:28:05 2020', 'user': {'account_name': 'Guest'}}
2020-02-01 10:28:07,590 DEBUG decorators.py log_writter вызывается функция process_client_message из модуля __main__функции переданы параметры ({'action': 'presence', 'time': 'Sat Feb  1 10:28:05 2020', 'user': {'account_name': 'Guest'}},),{}функция вернула {'response': 200}.была вызвана из main()
2020-02-01 10:28:07,590 INFO my_server.py main Cформирован ответ клиенту "{'response': 200}"
2020-02-01 10:28:07,590 INFO my_server.py main Клиенту ('127.0.0.1', 55997) отправлено сообщение "{'response': 200}"
2020-02-01 10:28:07,591 INFO my_server.py main Соединение c клиентом ('127.0.0.1', 55997) закрывается
2020-02-01 10:28:13,372 DEBUG decorators.py log_writter вызывается функция process_server_ans из модуля __main__функции переданы параметры ({'response': 200},),{}функция вернула 200 : OK.была вызвана из main()
2020-02-01 10:42:43,754 DEBUG my_server.py main При запуске переданы аргументы: Namespace(ip_addr='127.0.0.1', port=7777)
2020-02-01 10:42:43,755 INFO my_server.py main Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: 127.0.0.1. Если адрес не указан, принимаются соединения с любых адресов.
2020-02-01 10:42:54,809 INFO my_server.py main Установлено соедение с Клиентом ('127.0.0.1', 56156)
2020-02-01 10:42:54,810 DEBUG decorators.py log_writter вызывается функция generate_presence_msg из модуля __main__функции переданы параметры (),{}функция вернула {'action': 'presence', 'time': 'Sat Feb  1 10:42:54 2020', 'user': {'account_name': 'Guest'}}.была вызвана из main()
2020-02-01 10:42:54,810 DEBUG my_server.py main От клиента ('127.0.0.1', 56156) получено сообщение: {'action': 'presence', 'time': 'Sat Feb  1 10:42:54 2020', 'user': {'account_name': 'Guest'}}
2020-02-01 10:42:54,811 DEBUG decorators.py log_writter вызывается функция process_client_message из модуля __main__функции переданы параметры ({'action': 'presence', 'time': 'Sat Feb  1 10:42:54 2020', 'user': {'account_name': 'Guest'}},),{}функция вернула {'response': 200}.была вызвана из main()
2020-02-01 10:42:54,811 INFO my_server.py main Cформирован ответ клиенту "{'response': 200}"
2020-02-01 10:42:54,811 INFO my_server.py main Клиенту ('127.0.0.1', 56156) отправлено сообщение "{'response': 200}"
2020-02-01 10:42:54,812 INFO my_server.py main Соединение c клиентом ('127.0.0.1', 56156) закрывается
2020-02-01 10:42:54,812 DEBUG decorators.py log_writter вызывается функция process_server_ans из модуля __main__функции переданы параметры ({'response': 200},),{}функция вернула 200 : OK.была вызвана из main()
